version: '3.1'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - helpdesk_postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: helpdesk_history_db
        MONGO_INITDB_ROOT_USERNAME: user
        MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - helpdesk_mongo_data:/data/db    

volumes:
  helpdesk_postgres_data:
  helpdesk_mongo_data:
