version: '3.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: helpdesk_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - helpdesk_postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: helpdesk_history_db
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - helpdesk_mongo_data:/data/db    
     eureka-server:
    image: helpdesk/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    expose:
      - "8761"

  config-server:
    image: helpdesk/config-server:latest
    container_name: config-server
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  gateway-service:
    image: helpdesk/gateway-service:latest
    container_name: gateway-service
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      eureka.client.enabled: 'true'
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
    depends_on:
      - config-server

volumes:
  helpdesk_postgres_data:
  helpdesk_mongo_data:
